// DESCRIPTION:
// Write a function that takes an array of numbers and returns the sum of the numbers. The numbers can be negative or non-integer. If the array does not contain any numbers then you should return 0.
// my awnser was 

// def sum_array(a):
//     if sum(a) == 0:
//         return 0
//     else:
//         return sum(a)
    
//     return a

function sum_array(a){
    if(sum (a) === 0)
        console.log(0)
    else
        console.log(sum(a))
}
    